//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PullToScxtpt.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.common.yinhai.com/")]
    public partial class UnsupportedEncodingException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.common.yinhai.com/", ConfigurationName="ServiceReference1.YinHaiBusiness")]
    public interface YinHaiBusiness {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PullToScxtpt.ServiceReference1.UnsupportedEncodingException), Action="", Name="UnsupportedEncodingException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PullToScxtpt.ServiceReference1.callBusinessGzipResponse callBusinessGzip(PullToScxtpt.ServiceReference1.callBusinessGzip request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.callBusinessGzipResponse> callBusinessGzipAsync(PullToScxtpt.ServiceReference1.callBusinessGzip request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PullToScxtpt.ServiceReference1.getJylshResponse getJylsh(PullToScxtpt.ServiceReference1.getJylsh request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.getJylshResponse> getJylshAsync(PullToScxtpt.ServiceReference1.getJylsh request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PullToScxtpt.ServiceReference1.callBusinessResponse callBusiness(PullToScxtpt.ServiceReference1.callBusiness request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.callBusinessResponse> callBusinessAsync(PullToScxtpt.ServiceReference1.callBusiness request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PullToScxtpt.ServiceReference1.cancelBusinessResponse cancelBusiness(PullToScxtpt.ServiceReference1.cancelBusiness request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.cancelBusinessResponse> cancelBusinessAsync(PullToScxtpt.ServiceReference1.cancelBusiness request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PullToScxtpt.ServiceReference1.confirmBusinessResponse confirmBusiness(PullToScxtpt.ServiceReference1.confirmBusiness request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.confirmBusinessResponse> confirmBusinessAsync(PullToScxtpt.ServiceReference1.confirmBusiness request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="callBusinessGzip", WrapperNamespace="http://webservice.common.yinhai.com/", IsWrapped=true)]
    public partial class callBusinessGzip {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.common.yinhai.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] inputByte;
        
        public callBusinessGzip() {
        }
        
        public callBusinessGzip(byte[] inputByte) {
            this.inputByte = inputByte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="callBusinessGzipResponse", WrapperNamespace="http://webservice.common.yinhai.com/", IsWrapped=true)]
    public partial class callBusinessGzipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.common.yinhai.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public callBusinessGzipResponse() {
        }
        
        public callBusinessGzipResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJylsh", WrapperNamespace="http://webservice.common.yinhai.com/", IsWrapped=true)]
    public partial class getJylsh {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.common.yinhai.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inputxml;
        
        public getJylsh() {
        }
        
        public getJylsh(string inputxml) {
            this.inputxml = inputxml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getJylshResponse", WrapperNamespace="http://webservice.common.yinhai.com/", IsWrapped=true)]
    public partial class getJylshResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.common.yinhai.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getJylshResponse() {
        }
        
        public getJylshResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="callBusiness", WrapperNamespace="http://webservice.common.yinhai.com/", IsWrapped=true)]
    public partial class callBusiness {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.common.yinhai.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inputxml;
        
        public callBusiness() {
        }
        
        public callBusiness(string inputxml) {
            this.inputxml = inputxml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="callBusinessResponse", WrapperNamespace="http://webservice.common.yinhai.com/", IsWrapped=true)]
    public partial class callBusinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.common.yinhai.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public callBusinessResponse() {
        }
        
        public callBusinessResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelBusiness", WrapperNamespace="http://webservice.common.yinhai.com/", IsWrapped=true)]
    public partial class cancelBusiness {
        
        public cancelBusiness() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelBusinessResponse", WrapperNamespace="http://webservice.common.yinhai.com/", IsWrapped=true)]
    public partial class cancelBusinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.common.yinhai.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public cancelBusinessResponse() {
        }
        
        public cancelBusinessResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmBusiness", WrapperNamespace="http://webservice.common.yinhai.com/", IsWrapped=true)]
    public partial class confirmBusiness {
        
        public confirmBusiness() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmBusinessResponse", WrapperNamespace="http://webservice.common.yinhai.com/", IsWrapped=true)]
    public partial class confirmBusinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.common.yinhai.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public confirmBusinessResponse() {
        }
        
        public confirmBusinessResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface YinHaiBusinessChannel : PullToScxtpt.ServiceReference1.YinHaiBusiness, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class YinHaiBusinessClient : System.ServiceModel.ClientBase<PullToScxtpt.ServiceReference1.YinHaiBusiness>, PullToScxtpt.ServiceReference1.YinHaiBusiness {
        
        public YinHaiBusinessClient() {
        }
        
        public YinHaiBusinessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public YinHaiBusinessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YinHaiBusinessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YinHaiBusinessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PullToScxtpt.ServiceReference1.callBusinessGzipResponse PullToScxtpt.ServiceReference1.YinHaiBusiness.callBusinessGzip(PullToScxtpt.ServiceReference1.callBusinessGzip request) {
            return base.Channel.callBusinessGzip(request);
        }
        
        public byte[] callBusinessGzip(byte[] inputByte) {
            PullToScxtpt.ServiceReference1.callBusinessGzip inValue = new PullToScxtpt.ServiceReference1.callBusinessGzip();
            inValue.inputByte = inputByte;
            PullToScxtpt.ServiceReference1.callBusinessGzipResponse retVal = ((PullToScxtpt.ServiceReference1.YinHaiBusiness)(this)).callBusinessGzip(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.callBusinessGzipResponse> PullToScxtpt.ServiceReference1.YinHaiBusiness.callBusinessGzipAsync(PullToScxtpt.ServiceReference1.callBusinessGzip request) {
            return base.Channel.callBusinessGzipAsync(request);
        }
        
        public System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.callBusinessGzipResponse> callBusinessGzipAsync(byte[] inputByte) {
            PullToScxtpt.ServiceReference1.callBusinessGzip inValue = new PullToScxtpt.ServiceReference1.callBusinessGzip();
            inValue.inputByte = inputByte;
            return ((PullToScxtpt.ServiceReference1.YinHaiBusiness)(this)).callBusinessGzipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PullToScxtpt.ServiceReference1.getJylshResponse PullToScxtpt.ServiceReference1.YinHaiBusiness.getJylsh(PullToScxtpt.ServiceReference1.getJylsh request) {
            return base.Channel.getJylsh(request);
        }
        
        public string getJylsh(string inputxml) {
            PullToScxtpt.ServiceReference1.getJylsh inValue = new PullToScxtpt.ServiceReference1.getJylsh();
            inValue.inputxml = inputxml;
            PullToScxtpt.ServiceReference1.getJylshResponse retVal = ((PullToScxtpt.ServiceReference1.YinHaiBusiness)(this)).getJylsh(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.getJylshResponse> PullToScxtpt.ServiceReference1.YinHaiBusiness.getJylshAsync(PullToScxtpt.ServiceReference1.getJylsh request) {
            return base.Channel.getJylshAsync(request);
        }
        
        public System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.getJylshResponse> getJylshAsync(string inputxml) {
            PullToScxtpt.ServiceReference1.getJylsh inValue = new PullToScxtpt.ServiceReference1.getJylsh();
            inValue.inputxml = inputxml;
            return ((PullToScxtpt.ServiceReference1.YinHaiBusiness)(this)).getJylshAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PullToScxtpt.ServiceReference1.callBusinessResponse PullToScxtpt.ServiceReference1.YinHaiBusiness.callBusiness(PullToScxtpt.ServiceReference1.callBusiness request) {
            return base.Channel.callBusiness(request);
        }
        
        public string callBusiness(string inputxml) {
            PullToScxtpt.ServiceReference1.callBusiness inValue = new PullToScxtpt.ServiceReference1.callBusiness();
            inValue.inputxml = inputxml;
            PullToScxtpt.ServiceReference1.callBusinessResponse retVal = ((PullToScxtpt.ServiceReference1.YinHaiBusiness)(this)).callBusiness(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.callBusinessResponse> PullToScxtpt.ServiceReference1.YinHaiBusiness.callBusinessAsync(PullToScxtpt.ServiceReference1.callBusiness request) {
            return base.Channel.callBusinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.callBusinessResponse> callBusinessAsync(string inputxml) {
            PullToScxtpt.ServiceReference1.callBusiness inValue = new PullToScxtpt.ServiceReference1.callBusiness();
            inValue.inputxml = inputxml;
            return ((PullToScxtpt.ServiceReference1.YinHaiBusiness)(this)).callBusinessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PullToScxtpt.ServiceReference1.cancelBusinessResponse PullToScxtpt.ServiceReference1.YinHaiBusiness.cancelBusiness(PullToScxtpt.ServiceReference1.cancelBusiness request) {
            return base.Channel.cancelBusiness(request);
        }
        
        public string cancelBusiness() {
            PullToScxtpt.ServiceReference1.cancelBusiness inValue = new PullToScxtpt.ServiceReference1.cancelBusiness();
            PullToScxtpt.ServiceReference1.cancelBusinessResponse retVal = ((PullToScxtpt.ServiceReference1.YinHaiBusiness)(this)).cancelBusiness(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.cancelBusinessResponse> PullToScxtpt.ServiceReference1.YinHaiBusiness.cancelBusinessAsync(PullToScxtpt.ServiceReference1.cancelBusiness request) {
            return base.Channel.cancelBusinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.cancelBusinessResponse> cancelBusinessAsync() {
            PullToScxtpt.ServiceReference1.cancelBusiness inValue = new PullToScxtpt.ServiceReference1.cancelBusiness();
            return ((PullToScxtpt.ServiceReference1.YinHaiBusiness)(this)).cancelBusinessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PullToScxtpt.ServiceReference1.confirmBusinessResponse PullToScxtpt.ServiceReference1.YinHaiBusiness.confirmBusiness(PullToScxtpt.ServiceReference1.confirmBusiness request) {
            return base.Channel.confirmBusiness(request);
        }
        
        public string confirmBusiness() {
            PullToScxtpt.ServiceReference1.confirmBusiness inValue = new PullToScxtpt.ServiceReference1.confirmBusiness();
            PullToScxtpt.ServiceReference1.confirmBusinessResponse retVal = ((PullToScxtpt.ServiceReference1.YinHaiBusiness)(this)).confirmBusiness(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.confirmBusinessResponse> PullToScxtpt.ServiceReference1.YinHaiBusiness.confirmBusinessAsync(PullToScxtpt.ServiceReference1.confirmBusiness request) {
            return base.Channel.confirmBusinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<PullToScxtpt.ServiceReference1.confirmBusinessResponse> confirmBusinessAsync() {
            PullToScxtpt.ServiceReference1.confirmBusiness inValue = new PullToScxtpt.ServiceReference1.confirmBusiness();
            return ((PullToScxtpt.ServiceReference1.YinHaiBusiness)(this)).confirmBusinessAsync(inValue);
        }
    }
}
